version: '3'
services:
  slackbot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app/plugins/:/app/plugins/
      - ./requirements.txt:/requirements.txt
    environment:
      - DEFAULT_REPLY=Squak?
      - API_TOKEN=YOUR_API_TOKEN
      - SHODAN_TOKEN=YOUR_SODAN_TOKEN

