version: '3'
services:
  slackbot:
    image: okwrtdsh/slackbot:latest
    volumes:
      - ./app/plugins/:/app/plugins/
      - ./requirements.txt:/requirements.txt
    environment:
      - DEFAULT_REPLY=Squak?
      - API_TOKEN=SLACK_API_TOKEN
      - SHODAN_TOKEN=SHODAN_API_TOKEN
